modLoader="javafml" #mandatory
loaderVersion="[39,)" 
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" 
[[mods]] 
modId="shelve"
version="0.1.2"
displayName="Shelve" 
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png" 
credits="Shelve by Matterssstream" 
authors="Matterssstream" 
description='''
Click to add a title.
'''
[[dependencies.shelve]] 
    modId="forge" 
    mandatory=true 
    versionRange="[40,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.shelve]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
